const PERFIS = {
  JOGADOR: 'JOGADOR',
  ADMINISTRADOR: 'ADMINISTRADOR'
};

const TIPOS_REQUISITO = {
  RF: 'RF',
  RNF: 'RNF',
  RN: 'RN'
};

const NAO_CONDIZ_COM_TEMA = 'NAO_CONDIZ_COM_TEMA';

const RESPOSTAS_POSSIVEIS = [
  TIPOS_REQUISITO.RF,
  TIPOS_REQUISITO.RNF,
  TIPOS_REQUISITO.RN,
  NAO_CONDIZ_COM_TEMA
];

module.exports = { PERFIS, TIPOS_REQUISITO, NAO_CONDIZ_COM_TEMA, RESPOSTAS_POSSIVEIS };
